Sync with upstream
Code now up to date with
https://github.com/civicrm/civicrm-buildkit/commit/01f9f29847be11ebcc62229b953af382113e708b

command used

git pull upstream master -s recursive -X theirs --squash

Wishlist - get rid of our repo - use upstream directly.
Failing that wipe our repo clean, start again from master,
auto-sync

Change-Id: Ibdabc21fe21afa6a4b6f0b507232acd46ed9ba02

diff --git a/bin/civi-download-tools b/bin/civi-download-tools
--- a/bin/civi-download-tools
+++ b/bin/civi-download-tools
@@ -356,7 +356,7 @@ function get_system_installer() {
     source /etc/lsb-release
   fi
   case "$DISTRIB_CODENAME" in
-    stretch|buster|xenial|bionic|disco|focal)
+    stretch|buster|bionic|focal|hirsute)
       echo "do_system_$DISTRIB_CODENAME"
       ;;
     *)
@@ -367,9 +367,9 @@ function get_system_installer() {
 
 ###############################################################################
 
-function do_system_xenial() {
+function do_system_xenial() { # LTS Removal Oct 2021
   set -e
-    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.1-cli php7.1-imap php7.1-ldap php7.1-curl php7.1-mysql php7.1-intl php7.1-gd php7.1-mcrypt php7.1-bcmath php7.1-mbstring php7.1-soap php7.1-zip php7.1-xml apache2 libapache2-mod-php7.1 nodejs"
+    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.3-cli php7.3-imap php7.3-ldap php7.3-curl php7.3-mysql php7.3-intl php7.3-gd php7.3-mcrypt php7.3-bcmath php7.3-mbstring php7.3-soap php7.3-zip php7.3-xml apache2 libapache2-mod-php7.3 nodejs"
     UBUNTU_VERSION=$(lsb_release -ds)
     echo "Detected $UBUNTU_VERSION."
     echo ""
@@ -379,7 +379,7 @@ function do_system_xenial() {
     echo ""
     if cvutil_confirm "Run automated installation? [Y/n] " y y; then
       sudo add-apt-repository -y ppa:ondrej/php
-      sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
+      sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
       sudo apt-get update
       sudo apt-get -y install $PACKAGES
       sudo phpenmod bcmath
@@ -397,9 +397,9 @@ function do_system_xenial() {
 
 ###############################################################################
 
-function do_system_bionic() {
+function do_system_bionic() { # LTS Removal October 2023
   set -e
-    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.2-cli php7.2-imap php7.2-ldap php7.2-curl php7.2-mysql php7.2-intl php7.2-gd php7.2-dev php7.2-bcmath php7.2-mbstring php7.2-soap php7.2-zip php7.2-xml apache2 libapache2-mod-php7.2 nodejs php-pear libmcrypt-dev libreadline-dev curl"
+    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.3-cli php7.3-imap php7.3-ldap php7.3-curl php7.3-mysql php7.3-intl php7.3-gd php7.3-dev php7.3-bcmath php7.3-mbstring php7.3-soap php7.3-zip php7.3-xml apache2 libapache2-mod-php7.3 nodejs php-pear libmcrypt-dev libreadline-dev curl"
     UBUNTU_VERSION=$(lsb_release -ds)
     echo "Detected $UBUNTU_VERSION."
     echo ""
@@ -409,7 +409,7 @@ function do_system_bionic() {
     echo ""
     if cvutil_confirm "Run automated installation? [Y/n] " y y; then
       sudo add-apt-repository -y ppa:ondrej/php
-      sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
+      sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
       sudo apt-get -y install $PACKAGES
       sudo phpenmod bcmath
       sudo phpenmod curl
@@ -426,36 +426,7 @@ function do_system_bionic() {
 
 ###############################################################################
 
-function do_system_disco() {
-  set -e
-    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.2-cli php7.2-imap php7.2-ldap php7.2-curl php7.2-mysql php7.2-intl php7.2-gd php7.2-dev php7.2-bcmath php7.2-mbstring php7.2-soap php7.2-zip php7.2-xml apache2 libapache2-mod-php7.2 nodejs php-pear libmcrypt-dev libreadline-dev curl"
-    UBUNTU_VERSION=$(lsb_release -ds)
-    echo "Detected $UBUNTU_VERSION."
-    echo ""
-    echo "Task: $PACKAGES"
-    echo ""
-    do_php_mysql_warning
-    echo ""
-    if cvutil_confirm "Run automated installation? [Y/n] " y y; then
-      sudo add-apt-repository -y ppa:ondrej/php
-      sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
-      sudo apt-get -y install $PACKAGES
-      sudo phpenmod bcmath
-      sudo phpenmod curl
-      sudo phpenmod imap
-      sudo phpenmod xml
-      sudo a2enmod rewrite
-      sudo apache2ctl restart
-    else
-      echo "Aborted" 1>&2
-      exit 1
-    fi
-  set +e
-}
-
-###############################################################################
-
-function do_system_focal() {
+function do_system_focal() { # LTS Removal October 2025
   set -e
     PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.3-cli php7.3-imap php7.3-ldap php7.3-curl php7.3-mysql php7.3-intl php7.3-gd php7.3-dev php7.3-bcmath php7.3-mbstring php7.3-soap php7.3-zip php7.3-xml apache2 libapache2-mod-php7.3 nodejs php-pear libreadline-dev curl"
     UBUNTU_VERSION=$(lsb_release -ds)
@@ -467,7 +438,36 @@ function do_system_focal() {
     echo ""
     if cvutil_confirm "Run automated installation? [Y/n] " y y; then
       sudo add-apt-repository -y ppa:ondrej/php
-      sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
+      sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
+      sudo apt-get -y install $PACKAGES
+      sudo phpenmod bcmath
+      sudo phpenmod curl
+      sudo phpenmod imap
+      sudo phpenmod xml
+      sudo a2enmod rewrite
+      sudo apache2ctl restart
+    else
+      echo "Aborted" 1>&2
+      exit 1
+    fi
+  set +e
+}
+
+###############################################################################
+
+function do_system_hirsute() { # Non-LTS Removal July 2022
+  set -e
+    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.3-cli php7.3-imap php7.3-ldap php7.3-curl php7.3-mysql php7.3-intl php7.3-gd php7.3-dev php7.3-bcmath php7.3-mbstring php7.3-soap php7.3-zip php7.3-xml apache2 libapache2-mod-php7.3 nodejs php-pear libreadline-dev curl"
+    UBUNTU_VERSION=$(lsb_release -ds)
+    echo "Detected $UBUNTU_VERSION."
+    echo ""
+    echo "Task: $PACKAGES"
+    echo ""
+    do_php_mysql_warning
+    echo ""
+    if cvutil_confirm "Run automated installation? [Y/n] " y y; then
+      sudo add-apt-repository -y ppa:ondrej/php
+      sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - # This runs sudo apt update so there's no point running it twice.
       sudo apt-get -y install $PACKAGES
       sudo phpenmod bcmath
       sudo phpenmod curl
@@ -486,7 +486,7 @@ function do_system_focal() {
 
 function do_system_stretch() {
   set -e
-    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.2-cli php7.2-imap php7.2-ldap php7.2-curl php7.2-mysql php7.2-intl php7.2-gd php7.2-dev php7.2-bcmath php7.2-mbstring php7.2-soap php7.2-zip php7.2-xml apache2 libapache2-mod-php7.2 nodejs"
+    PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.3-cli php7.3-imap php7.3-ldap php7.3-curl php7.3-mysql php7.3-intl php7.3-gd php7.3-dev php7.3-bcmath php7.3-mbstring php7.3-soap php7.3-zip php7.3-xml apache2 libapache2-mod-php7.3 nodejs"
     echo "Detected \"Debian Stretch\"."
     echo ""
     echo "Installing nodejs Debian repository."
@@ -499,7 +499,7 @@ function do_system_stretch() {
       sudo apt-get -y install ca-certificates apt-transport-https wget
       wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
       sudo echo "deb https://packages.sury.org/php/ stretch main" | tee /etc/apt/sources.list.d/php.list
-      wget -O- https://deb.nodesource.com/setup_10.x | sudo -E bash -
+      wget -O- https://deb.nodesource.com/setup_14.x | sudo -E bash -
       sudo apt-get -y install $PACKAGES
       sudo phpenmod imap
       sudo a2enmod rewrite
@@ -524,6 +524,7 @@ function do_system_buster() {
       sudo apt-get -y install ca-certificates apt-transport-https wget
       wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
       sudo echo "deb https://packages.sury.org/php/ buster main" | tee /etc/apt/sources.list.d/php.list
+      wget -O- https://deb.nodesource.com/setup_14.x | sudo -E bash -
       sudo apt-get -y install $PACKAGES
       sudo phpenmod imap
       sudo a2enmod rewrite
